admin_controllers:
  resource: ../../src/Controller/Admin
  prefix: /admin
  name_prefix: admin_
  type: annotation

user_controllers:
  resource: ../../src/Controller/User
  type: annotation

default_controllers:
  resource: ../../src/Controller/Default
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
